spring:
  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://127.0.0.1:6041/td?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
    # 当前使用的是JDBC-RESTful方式，如使用JDBC-JNI，需要做如下切换
    # driver-class-name: com.taosdata.jdbc.TSDBDriver
    # url: jdbc:TAOS://localhost:6041/?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
    username: root
    password: taosdata
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      validation-query: select server_status();
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 打印sql，开发测试时开启
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
